SOURCES := ../agda
MODULES := Background Notation Examples Properties Tests
PROTECT := docs/index.md docs/Abstract.md docs/Library/index.md docs/Meta-notation.md
SERVER  := 8026

include agda-pages/agda-pages.mk
