nav:
  - About:
    - index.md
    - meta-notation.md
  - Lambda-Calculus:
    - LC/index.md
    - LC/*
  - PCF:
    - PCF/index.md
    - PCF/*
  - Scm:
    - Scm/index.md
    - Scm/*
  - Notation.md
  - Library:
    - Library/index.md
    - '*'
  
preserve_directory_names: true

sort:
  sections: mixed